version: "3"

services:
  elysium-processor-db:
    image: postgres:12
    restart: always
    container_name: elysium-processor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  elysium-processor:
    image: subsquid-processor:3
    container_name: elysium-processor
    restart: always
    depends_on:
     - "elysium-processor-db"
    environment:
     DB_HOST: elysium-processor-db
     DB_PORT: 5432
     DB_NAME: squid
     DB_USER: postgres
     DB_PASS: squid
     CHAIN: atlantis
     FROM: 900000
     PROCESSOR_PROMETHEUS_PORT: 3000
     GQL_PORT: 4350
     TOKEN_BASE_URI: https://mypinata.cloud/ipfs/
  elysium-graphql:
    image: graphql:1
    container_name: elysium-graphql
    restart: always
    depends_on:
     - "elysium-processor-db"
    environment:
     DB_HOST: elysium-processor-db
     DB_PORT: 5432
     DB_NAME: squid
     DB_USER: postgres
     DB_PASS: squid
     CHAIN: atlantis
     FROM: 900000
     PROCESSOR_PROMETHEUS_PORT: 3000
     GQL_PORT: 4350
     TOKEN_BASE_URI: https://mypinata.cloud/ipfs/
    ports:
     - 4350:4350
