version: "3"

services:
  db:
    container_name: squid-giant
    image: firesquid:1
    environment:
      DB_NAME: squid
      DB_PASS: squid
      DB_PORT: 23798
      PROCESSOR_PROMETHEUS_PORT: 3000
      GQL_PORT: 4000
      CHAIN: atlantis
      FROM: 900000
    ports:
      - "4000:4000"
      # command: ["postgres", "-c", "log_statement=all"]
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

